deploy:
  docker:
    - image: cibuilds/hugo:0.42.1
  steps:
    - attach_workspace:
        at: src
    - add_ssh_keys
    - run: |
        echo 'web01.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJiGRY6N9WYQ0vy6cTiwAgNbc6ueJmVo/EafBtmT7bcD6cQMbipYM/KfYQ2lCn2TxqWepZKYoyoVQXgArycCOns=' >> ~/.ssh/known_hosts
        rsync -va --delete src/public/ staticweb@web01.revidian.net:www/feliciano.tech/public_html